version: '2'
services:
    filebeat:
        build: .
        image: [ваш imageId образа filebeat]
        volumes:
            - /path/to/myElk/log/nginx:/etc/logs/nginx 
            - /path/to/myElk/filebeat:/etc/filebeat
            - /path/to/myElk/filebeat/tmp:/tmp/filebeat